#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = %cd%

CC = gcc.exe
CXX = g++.exe
AR = ar.exe
LD = g++.exe
WINDRES = windres.exe

INC = 
CFLAGS = -Wall
RESINC = 
LIBDIR = 
LIB = -lgdi32 -luser32 -lkernel32 -lcomctl32
LDFLAGS = 

INC_DEBUG = $(INC) -Iinclude
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB) 
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj\\Debug
DEP_DEBUG = 
OUT_DEBUG = bin\\Debug\\Snake++.exe

INC_RELEASE = $(INC) -Iinclude
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB) 
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj\\Release
DEP_RELEASE = 
OUT_RELEASE = bin\\Release\\Snake++.exe

OBJ_DEBUG = $(OBJDIR_DEBUG)\\src\\obstacle.o $(OBJDIR_DEBUG)\\src\\funcs.o $(OBJDIR_DEBUG)\\src\\Snake.o $(OBJDIR_DEBUG)\\src\\Game.o $(OBJDIR_DEBUG)\\src\\Fruit.o $(OBJDIR_DEBUG)\\src\\Board.o $(OBJDIR_DEBUG)\\main.o

OBJ_RELEASE = $(OBJDIR_RELEASE)\\src\\obstacle.o $(OBJDIR_RELEASE)\\src\\funcs.o $(OBJDIR_RELEASE)\\src\\Snake.o $(OBJDIR_RELEASE)\\src\\Game.o $(OBJDIR_RELEASE)\\src\\Fruit.o $(OBJDIR_RELEASE)\\src\\Board.o $(OBJDIR_RELEASE)\\main.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	cmd /c if not exist bin\\Debug md bin\\Debug
	cmd /c if not exist $(OBJDIR_DEBUG)\\src md $(OBJDIR_DEBUG)\\src
	cmd /c if not exist $(OBJDIR_DEBUG) md $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)\\src\\obstacle.o: src\\obstacle.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\obstacle.cpp -o $(OBJDIR_DEBUG)\\src\\obstacle.o

$(OBJDIR_DEBUG)\\src\\funcs.o: src\\funcs.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\funcs.cpp -o $(OBJDIR_DEBUG)\\src\\funcs.o

$(OBJDIR_DEBUG)\\src\\Snake.o: src\\Snake.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\Snake.cpp -o $(OBJDIR_DEBUG)\\src\\Snake.o

$(OBJDIR_DEBUG)\\src\\Game.o: src\\Game.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\Game.cpp -o $(OBJDIR_DEBUG)\\src\\Game.o

$(OBJDIR_DEBUG)\\src\\Fruit.o: src\\Fruit.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\Fruit.cpp -o $(OBJDIR_DEBUG)\\src\\Fruit.o

$(OBJDIR_DEBUG)\\src\\Board.o: src\\Board.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\Board.cpp -o $(OBJDIR_DEBUG)\\src\\Board.o

$(OBJDIR_DEBUG)\\main.o: main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.cpp -o $(OBJDIR_DEBUG)\\main.o

clean_debug: 
	cmd /c del /f $(OBJ_DEBUG) $(OUT_DEBUG)
	cmd /c rd bin\\Debug
	cmd /c rd $(OBJDIR_DEBUG)\\src
	cmd /c rd $(OBJDIR_DEBUG)

before_release: 
	cmd /c if not exist bin\\Release md bin\\Release
	cmd /c if not exist $(OBJDIR_RELEASE)\\src md $(OBJDIR_RELEASE)\\src
	cmd /c if not exist $(OBJDIR_RELEASE) md $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) -mwindows $(LIB_RELEASE)

$(OBJDIR_RELEASE)\\src\\obstacle.o: src\\obstacle.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\obstacle.cpp -o $(OBJDIR_RELEASE)\\src\\obstacle.o

$(OBJDIR_RELEASE)\\src\\funcs.o: src\\funcs.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\funcs.cpp -o $(OBJDIR_RELEASE)\\src\\funcs.o

$(OBJDIR_RELEASE)\\src\\Snake.o: src\\Snake.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\Snake.cpp -o $(OBJDIR_RELEASE)\\src\\Snake.o

$(OBJDIR_RELEASE)\\src\\Game.o: src\\Game.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\Game.cpp -o $(OBJDIR_RELEASE)\\src\\Game.o

$(OBJDIR_RELEASE)\\src\\Fruit.o: src\\Fruit.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\Fruit.cpp -o $(OBJDIR_RELEASE)\\src\\Fruit.o

$(OBJDIR_RELEASE)\\src\\Board.o: src\\Board.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\Board.cpp -o $(OBJDIR_RELEASE)\\src\\Board.o

$(OBJDIR_RELEASE)\\main.o: main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.cpp -o $(OBJDIR_RELEASE)\\main.o

clean_release: 
	cmd /c del /f $(OBJ_RELEASE) $(OUT_RELEASE)
	cmd /c rd bin\\Release
	cmd /c rd $(OBJDIR_RELEASE)\\src
	cmd /c rd $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

